prevent release if working copy is not clean

diff --git a/release b/release
--- a/release
+++ b/release
@@ -1,4 +1,20 @@
 #!/usr/bin/env bash
+set -e
+#sometimes git returns strange things...this seems to clear the bad state.
+git status &> /dev/null
+
+#check for unstaged tracked files
+if ! git diff-files --quiet; then
+	echo 'There are uncommitted changes. Aborting.'
+	exit 1
+fi
+
+#check for staged/not committed files
+if ! git diff-index --quiet --cached HEAD; then
+	echo 'There are uncommitted changes. Aborting.'
+	exit 1
+fi
+
 lerna publish --yes
 
 DIRS=packages/*
